# _config.yml
baseurl: ""  # 如果站点在根目录下
# 基础设置
title: "展示根目录的文件"
description: "自动生成根目录文件列表，并支持Markdown"
# baseurl: "/a"  # 生成的站点会存放在 /a 下
destination: .github/_site  # 生成的静态页面将存放在 .github/_site 目录下

# Markdown 支持
markdown: kramdown  # 确保支持Markdown格式

# 包含文件和目录的设置（包括根目录下的文件）
include:
  - assets
  - _posts
  - _data
  - _includes
  - _layouts
  - "*.md"  # 确保 Markdown 文件被包括
  - "**/*.md"  # 包括所有子目录中的 Markdown 文件

layouts_dir: ".github/_layouts"  # 设置布局目录为 .github/_layouts
plugins_dir: ".github/_plugins"  # 设置插件目录为 .github/_plugins

# 文件扩展名的设置，支持多种文件类型（Markdown、HTML等）
collections:
  markdown:
    output: true
    permalink: /:path/



