site_name: My site
site_url: https://mydomain.org/mysite
theme:
  name: material

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:  #数学公式
      generic: true